### ISSUE TITLE
[RFE] Azure KeyVault Support

### ISSUE THREAD

**Issue by xinity** [ondat/trousseau#139] opened 2022-07-21 12:38 UTC
The idea of the RFE is to see how we can leverage Azure Keyvault as an external KMS for trousseau.

What do we want to build?
ability to use Azure KeyVault as a KMS for Trousseau 

Why do we want to build it?
to offer Azure users an integrated solution that would release them from having to deploy another vault solution they will have to manage

**Comment by romdalf** [comment] 2022-07-21 14:29
We are bringing AWS support in v2 (a pre-release is ready) for the next milestone. 
From this work, a complete redesign has been done making it easier to onboard new KMS. 
I will create a new milestone and add Azure KeyVault in it.

**Comment by romdalf** [comment] 2022-07-26 10:46
addressed within #147

**Comment by romdalf** [comment] 2022-07-28 13:24
PR add support for Azure KeyVault #148 
Closing as duplicate of #147 - the issue to follow for final including documentation update

**Closed by romdalf** 2022-07-28 13:24 UTC
Labels: documentation, enhancement, help wanted, dependencies
